### ISSUE TITLE
Pull review

### ISSUE THREAD

**Issue by firstpj** [Sonikak004/Portfolio#9]
Great work on making the changes requested by a previous reviewer 👏

Good Effort
✔️ Your design is good.

Required Changes ♻️
Could you check the comments under the review?

-you'll need to check your lines and fix it.
-and in your HTML, try to close open spaces, it makes your code clean.

**Comment by Sonikak004** [comment]
Thank you for your review! I will fix the linters and also close the open spaces in html 👍
